[package]
name = "advent_of_code_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
fixed = "1.29.0"
kiddo = { version = "5.2.3", features = ["fixed"] }
log = "0.4.29"
regex = "1.12.2"
